/**
 * Every country the form offers, tied to the continent it is listed under.
 *
 * Generated once from CLDR through `Intl.DisplayNames` rather than read at
 * runtime: the browser and the server would each answer from their own ICU
 * build, and any difference between the two is a hydration mismatch on a
 * select the reader is halfway through using.
 *
 * Written as tuples, not objects — at nearly two hundred rows the keys would
 * be most of the file.
 */
export type CountryRow = readonly [
  code: string,
  continent: string,
  en: string,
  id: string,
];

export const COUNTRY_ROWS: readonly CountryRow[] = [
  ["DZ", "africa", "Algeria", "Aljazair"],
  ["AO", "africa", "Angola", "Angola"],
  ["BJ", "africa", "Benin", "Benin"],
  ["BW", "africa", "Botswana", "Botswana"],
  ["BF", "africa", "Burkina Faso", "Burkina Faso"],
  ["BI", "africa", "Burundi", "Burundi"],
  ["CM", "africa", "Cameroon", "Kamerun"],
  ["CV", "africa", "Cape Verde", "Tanjung Verde"],
  ["CF", "africa", "Central African Republic", "Republik Afrika Tengah"],
  ["TD", "africa", "Chad", "Chad"],
  ["KM", "africa", "Comoros", "Komoro"],
  ["CG", "africa", "Congo - Brazzaville", "Kongo - Brazzaville"],
  ["CD", "africa", "Congo - Kinshasa", "Kongo - Kinshasa"],
  ["CI", "africa", "Côte d’Ivoire", "Côte d’Ivoire"],
  ["DJ", "africa", "Djibouti", "Jibuti"],
  ["EG", "africa", "Egypt", "Mesir"],
  ["GQ", "africa", "Equatorial Guinea", "Guinea Ekuatorial"],
  ["ER", "africa", "Eritrea", "Eritrea"],
  ["SZ", "africa", "Eswatini", "eSwatini"],
  ["ET", "africa", "Ethiopia", "Etiopia"],
  ["GA", "africa", "Gabon", "Gabon"],
  ["GM", "africa", "Gambia", "Gambia"],
  ["GH", "africa", "Ghana", "Ghana"],
  ["GN", "africa", "Guinea", "Guinea"],
  ["GW", "africa", "Guinea-Bissau", "Guinea-Bissau"],
  ["KE", "africa", "Kenya", "Kenya"],
  ["LS", "africa", "Lesotho", "Lesotho"],
  ["LR", "africa", "Liberia", "Liberia"],
  ["LY", "africa", "Libya", "Libya"],
  ["MG", "africa", "Madagascar", "Madagaskar"],
  ["MW", "africa", "Malawi", "Malawi"],
  ["ML", "africa", "Mali", "Mali"],
  ["MR", "africa", "Mauritania", "Mauritania"],
  ["MU", "africa", "Mauritius", "Mauritius"],
  ["MA", "africa", "Morocco", "Maroko"],
  ["MZ", "africa", "Mozambique", "Mozambik"],
  ["NA", "africa", "Namibia", "Namibia"],
  ["NE", "africa", "Niger", "Niger"],
  ["NG", "africa", "Nigeria", "Nigeria"],
  ["RW", "africa", "Rwanda", "Rwanda"],
  ["ST", "africa", "São Tomé & Príncipe", "Sao Tome dan Principe"],
  ["SN", "africa", "Senegal", "Senegal"],
  ["SC", "africa", "Seychelles", "Seychelles"],
  ["SL", "africa", "Sierra Leone", "Sierra Leone"],
  ["SO", "africa", "Somalia", "Somalia"],
  ["ZA", "africa", "South Africa", "Afrika Selatan"],
  ["SS", "africa", "South Sudan", "Sudan Selatan"],
  ["SD", "africa", "Sudan", "Sudan"],
  ["TZ", "africa", "Tanzania", "Tanzania"],
  ["TG", "africa", "Togo", "Togo"],
  ["TN", "africa", "Tunisia", "Tunisia"],
  ["UG", "africa", "Uganda", "Uganda"],
  ["ZM", "africa", "Zambia", "Zambia"],
  ["ZW", "africa", "Zimbabwe", "Zimbabwe"],
  ["AF", "asia", "Afghanistan", "Afganistan"],
  ["AM", "asia", "Armenia", "Armenia"],
  ["AZ", "asia", "Azerbaijan", "Azerbaijan"],
  ["BH", "asia", "Bahrain", "Bahrain"],
  ["BD", "asia", "Bangladesh", "Bangladesh"],
  ["BT", "asia", "Bhutan", "Bhutan"],
  ["BN", "asia", "Brunei", "Brunei"],
  ["KH", "asia", "Cambodia", "Kamboja"],
  ["CN", "asia", "China", "Tiongkok"],
  ["CY", "asia", "Cyprus", "Siprus"],
  ["GE", "asia", "Georgia", "Georgia"],
  ["IN", "asia", "India", "India"],
  ["ID", "asia", "Indonesia", "Indonesia"],
  ["IR", "asia", "Iran", "Iran"],
  ["IQ", "asia", "Iraq", "Irak"],
  ["IL", "asia", "Israel", "Israel"],
  ["JP", "asia", "Japan", "Jepang"],
  ["JO", "asia", "Jordan", "Yordania"],
  ["KZ", "asia", "Kazakhstan", "Kazakhstan"],
  ["KW", "asia", "Kuwait", "Kuwait"],
  ["KG", "asia", "Kyrgyzstan", "Kirgizstan"],
  ["LA", "asia", "Laos", "Laos"],
  ["LB", "asia", "Lebanon", "Lebanon"],
  ["MY", "asia", "Malaysia", "Malaysia"],
  ["MV", "asia", "Maldives", "Maladewa"],
  ["MN", "asia", "Mongolia", "Mongolia"],
  ["MM", "asia", "Myanmar (Burma)", "Myanmar (Burma)"],
  ["NP", "asia", "Nepal", "Nepal"],
  ["KP", "asia", "North Korea", "Korea Utara"],
  ["OM", "asia", "Oman", "Oman"],
  ["PK", "asia", "Pakistan", "Pakistan"],
  ["PS", "asia", "Palestinian Territories", "Wilayah Palestina"],
  ["PH", "asia", "Philippines", "Filipina"],
  ["QA", "asia", "Qatar", "Qatar"],
  ["SA", "asia", "Saudi Arabia", "Arab Saudi"],
  ["SG", "asia", "Singapore", "Singapura"],
  ["KR", "asia", "South Korea", "Korea Selatan"],
  ["LK", "asia", "Sri Lanka", "Sri Lanka"],
  ["SY", "asia", "Syria", "Suriah"],
  ["TW", "asia", "Taiwan", "Taiwan"],
  ["TJ", "asia", "Tajikistan", "Tajikistan"],
  ["TH", "asia", "Thailand", "Thailand"],
  ["TL", "asia", "Timor-Leste", "Timor Leste"],
  ["TR", "asia", "Türkiye", "Turki"],
  ["TM", "asia", "Turkmenistan", "Turkmenistan"],
  ["AE", "asia", "United Arab Emirates", "Uni Emirat Arab"],
  ["UZ", "asia", "Uzbekistan", "Uzbekistan"],
  ["VN", "asia", "Vietnam", "Vietnam"],
  ["YE", "asia", "Yemen", "Yaman"],
  ["AL", "europe", "Albania", "Albania"],
  ["AD", "europe", "Andorra", "Andorra"],
  ["AT", "europe", "Austria", "Austria"],
  ["BY", "europe", "Belarus", "Belarus"],
  ["BE", "europe", "Belgium", "Belgia"],
  ["BA", "europe", "Bosnia & Herzegovina", "Bosnia dan Herzegovina"],
  ["BG", "europe", "Bulgaria", "Bulgaria"],
  ["HR", "europe", "Croatia", "Kroasia"],
  ["CZ", "europe", "Czechia", "Ceko"],
  ["DK", "europe", "Denmark", "Denmark"],
  ["EE", "europe", "Estonia", "Estonia"],
  ["FI", "europe", "Finland", "Finlandia"],
  ["FR", "europe", "France", "Prancis"],
  ["DE", "europe", "Germany", "Jerman"],
  ["GR", "europe", "Greece", "Yunani"],
  ["HU", "europe", "Hungary", "Hungaria"],
  ["IS", "europe", "Iceland", "Islandia"],
  ["IE", "europe", "Ireland", "Irlandia"],
  ["IT", "europe", "Italy", "Italia"],
  ["XK", "europe", "Kosovo", "Kosovo"],
  ["LV", "europe", "Latvia", "Latvia"],
  ["LI", "europe", "Liechtenstein", "Liechtenstein"],
  ["LT", "europe", "Lithuania", "Lituania"],
  ["LU", "europe", "Luxembourg", "Luksemburg"],
  ["MT", "europe", "Malta", "Malta"],
  ["MD", "europe", "Moldova", "Moldova"],
  ["MC", "europe", "Monaco", "Monako"],
  ["ME", "europe", "Montenegro", "Montenegro"],
  ["NL", "europe", "Netherlands", "Belanda"],
  ["MK", "europe", "North Macedonia", "Makedonia Utara"],
  ["NO", "europe", "Norway", "Norwegia"],
  ["PL", "europe", "Poland", "Polandia"],
  ["PT", "europe", "Portugal", "Portugal"],
  ["RO", "europe", "Romania", "Rumania"],
  ["RU", "europe", "Russia", "Rusia"],
  ["SM", "europe", "San Marino", "San Marino"],
  ["RS", "europe", "Serbia", "Serbia"],
  ["SK", "europe", "Slovakia", "Slovakia"],
  ["SI", "europe", "Slovenia", "Slovenia"],
  ["ES", "europe", "Spain", "Spanyol"],
  ["SE", "europe", "Sweden", "Swedia"],
  ["CH", "europe", "Switzerland", "Swiss"],
  ["UA", "europe", "Ukraine", "Ukraina"],
  ["GB", "europe", "United Kingdom", "Inggris Raya"],
  ["VA", "europe", "Vatican City", "Vatikan"],
  ["AG", "north-america", "Antigua & Barbuda", "Antigua dan Barbuda"],
  ["BS", "north-america", "Bahamas", "Bahama"],
  ["BB", "north-america", "Barbados", "Barbados"],
  ["BZ", "north-america", "Belize", "Belize"],
  ["CA", "north-america", "Canada", "Kanada"],
  ["CR", "north-america", "Costa Rica", "Kosta Rika"],
  ["CU", "north-america", "Cuba", "Kuba"],
  ["DM", "north-america", "Dominica", "Dominika"],
  ["DO", "north-america", "Dominican Republic", "Republik Dominika"],
  ["SV", "north-america", "El Salvador", "El Salvador"],
  ["GD", "north-america", "Grenada", "Grenada"],
  ["GT", "north-america", "Guatemala", "Guatemala"],
  ["HT", "north-america", "Haiti", "Haiti"],
  ["HN", "north-america", "Honduras", "Honduras"],
  ["JM", "north-america", "Jamaica", "Jamaika"],
  ["MX", "north-america", "Mexico", "Meksiko"],
  ["NI", "north-america", "Nicaragua", "Nikaragua"],
  ["PA", "north-america", "Panama", "Panama"],
  ["KN", "north-america", "St. Kitts & Nevis", "Saint Kitts dan Nevis"],
  ["LC", "north-america", "St. Lucia", "Saint Lucia"],
  ["VC", "north-america", "St. Vincent & Grenadines", "Saint Vincent dan Grenadine"],
  ["TT", "north-america", "Trinidad & Tobago", "Trinidad dan Tobago"],
  ["US", "north-america", "United States", "Amerika Serikat"],
  ["AU", "oceania", "Australia", "Australia"],
  ["FJ", "oceania", "Fiji", "Fiji"],
  ["KI", "oceania", "Kiribati", "Kiribati"],
  ["MH", "oceania", "Marshall Islands", "Kepulauan Marshall"],
  ["FM", "oceania", "Micronesia", "Mikronesia"],
  ["NR", "oceania", "Nauru", "Nauru"],
  ["NZ", "oceania", "New Zealand", "Selandia Baru"],
  ["PW", "oceania", "Palau", "Palau"],
  ["PG", "oceania", "Papua New Guinea", "Papua Nugini"],
  ["WS", "oceania", "Samoa", "Samoa"],
  ["SB", "oceania", "Solomon Islands", "Kepulauan Solomon"],
  ["TO", "oceania", "Tonga", "Tonga"],
  ["TV", "oceania", "Tuvalu", "Tuvalu"],
  ["VU", "oceania", "Vanuatu", "Vanuatu"],
  ["AR", "south-america", "Argentina", "Argentina"],
  ["BO", "south-america", "Bolivia", "Bolivia"],
  ["BR", "south-america", "Brazil", "Brasil"],
  ["CL", "south-america", "Chile", "Cile"],
  ["CO", "south-america", "Colombia", "Kolombia"],
  ["EC", "south-america", "Ecuador", "Ekuador"],
  ["GY", "south-america", "Guyana", "Guyana"],
  ["PY", "south-america", "Paraguay", "Paraguay"],
  ["PE", "south-america", "Peru", "Peru"],
  ["SR", "south-america", "Suriname", "Suriname"],
  ["UY", "south-america", "Uruguay", "Uruguay"],
  ["VE", "south-america", "Venezuela", "Venezuela"],
];
