/**
 * Every country the form offers, tied to the continent it is listed under and
 * to its international dialling code.
 *
 * Names are generated once from CLDR through `Intl.DisplayNames` rather than
 * read at runtime: the browser and the server would each answer from their own
 * ICU build, and any difference between the two is a hydration mismatch on a
 * select the reader is halfway through using.
 *
 * Dialling codes come from the committee's own spreadsheet, matched on the
 * Indonesian name. Six countries are not in that sheet — Cyprus, Jordan, El
 * Salvador, Guatemala, Honduras and Nicaragua — and carry their ITU codes
 * instead. Where a sheet entry lists two, the first is taken.
 *
 * Written as tuples, not objects — at nearly two hundred rows the keys would
 * be most of the file.
 */
export type CountryRow = readonly [
  code: string,
  continent: string,
  en: string,
  id: string,
  dial: string,
];

export const COUNTRY_ROWS: readonly CountryRow[] = [
  ["DZ", "africa", "Algeria", "Aljazair", "+213"],
  ["AO", "africa", "Angola", "Angola", "+244"],
  ["BJ", "africa", "Benin", "Benin", "+229"],
  ["BW", "africa", "Botswana", "Botswana", "+267"],
  ["BF", "africa", "Burkina Faso", "Burkina Faso", "+226"],
  ["BI", "africa", "Burundi", "Burundi", "+257"],
  ["CM", "africa", "Cameroon", "Kamerun", "+237"],
  ["CV", "africa", "Cape Verde", "Tanjung Verde", "+238"],
  ["CF", "africa", "Central African Republic", "Republik Afrika Tengah", "+236"],
  ["TD", "africa", "Chad", "Chad", "+235"],
  ["KM", "africa", "Comoros", "Komoro", "+269"],
  ["CG", "africa", "Congo - Brazzaville", "Kongo - Brazzaville", "+242"],
  ["CD", "africa", "Congo - Kinshasa", "Kongo - Kinshasa", "+243"],
  ["CI", "africa", "Côte d’Ivoire", "Côte d’Ivoire", "+225"],
  ["DJ", "africa", "Djibouti", "Jibuti", "+253"],
  ["EG", "africa", "Egypt", "Mesir", "+20"],
  ["GQ", "africa", "Equatorial Guinea", "Guinea Ekuatorial", "+240"],
  ["ER", "africa", "Eritrea", "Eritrea", "+291"],
  ["SZ", "africa", "Eswatini", "eSwatini", "+268"],
  ["ET", "africa", "Ethiopia", "Etiopia", "+251"],
  ["GA", "africa", "Gabon", "Gabon", "+241"],
  ["GM", "africa", "Gambia", "Gambia", "+220"],
  ["GH", "africa", "Ghana", "Ghana", "+233"],
  ["GN", "africa", "Guinea", "Guinea", "+224"],
  ["GW", "africa", "Guinea-Bissau", "Guinea-Bissau", "+245"],
  ["KE", "africa", "Kenya", "Kenya", "+254"],
  ["LS", "africa", "Lesotho", "Lesotho", "+266"],
  ["LR", "africa", "Liberia", "Liberia", "+231"],
  ["LY", "africa", "Libya", "Libya", "+218"],
  ["MG", "africa", "Madagascar", "Madagaskar", "+261"],
  ["MW", "africa", "Malawi", "Malawi", "+265"],
  ["ML", "africa", "Mali", "Mali", "+223"],
  ["MR", "africa", "Mauritania", "Mauritania", "+222"],
  ["MU", "africa", "Mauritius", "Mauritius", "+230"],
  ["MA", "africa", "Morocco", "Maroko", "+212"],
  ["MZ", "africa", "Mozambique", "Mozambik", "+258"],
  ["NA", "africa", "Namibia", "Namibia", "+264"],
  ["NE", "africa", "Niger", "Niger", "+227"],
  ["NG", "africa", "Nigeria", "Nigeria", "+234"],
  ["RW", "africa", "Rwanda", "Rwanda", "+250"],
  ["ST", "africa", "São Tomé & Príncipe", "Sao Tome dan Principe", "+239"],
  ["SN", "africa", "Senegal", "Senegal", "+221"],
  ["SC", "africa", "Seychelles", "Seychelles", "+248"],
  ["SL", "africa", "Sierra Leone", "Sierra Leone", "+232"],
  ["SO", "africa", "Somalia", "Somalia", "+252"],
  ["ZA", "africa", "South Africa", "Afrika Selatan", "+27"],
  ["SS", "africa", "South Sudan", "Sudan Selatan", "+211"],
  ["SD", "africa", "Sudan", "Sudan", "+249"],
  ["TZ", "africa", "Tanzania", "Tanzania", "+255"],
  ["TG", "africa", "Togo", "Togo", "+228"],
  ["TN", "africa", "Tunisia", "Tunisia", "+216"],
  ["UG", "africa", "Uganda", "Uganda", "+256"],
  ["ZM", "africa", "Zambia", "Zambia", "+260"],
  ["ZW", "africa", "Zimbabwe", "Zimbabwe", "+263"],
  ["AF", "asia", "Afghanistan", "Afganistan", "+93"],
  ["AM", "asia", "Armenia", "Armenia", "+374"],
  ["AZ", "asia", "Azerbaijan", "Azerbaijan", "+994"],
  ["BH", "asia", "Bahrain", "Bahrain", "+973"],
  ["BD", "asia", "Bangladesh", "Bangladesh", "+880"],
  ["BT", "asia", "Bhutan", "Bhutan", "+975"],
  ["BN", "asia", "Brunei", "Brunei", "+673"],
  ["KH", "asia", "Cambodia", "Kamboja", "+855"],
  ["CN", "asia", "China", "Tiongkok", "+86"],
  ["CY", "asia", "Cyprus", "Siprus", "+357"],
  ["GE", "asia", "Georgia", "Georgia", "+995"],
  ["IN", "asia", "India", "India", "+91"],
  ["ID", "asia", "Indonesia", "Indonesia", "+62"],
  ["IR", "asia", "Iran", "Iran", "+98"],
  ["IQ", "asia", "Iraq", "Irak", "+964"],
  ["IL", "asia", "Israel", "Israel", "+972"],
  ["JP", "asia", "Japan", "Jepang", "+81"],
  ["JO", "asia", "Jordan", "Yordania", "+962"],
  ["KZ", "asia", "Kazakhstan", "Kazakhstan", "+7"],
  ["KW", "asia", "Kuwait", "Kuwait", "+965"],
  ["KG", "asia", "Kyrgyzstan", "Kirgizstan", "+996"],
  ["LA", "asia", "Laos", "Laos", "+856"],
  ["LB", "asia", "Lebanon", "Lebanon", "+961"],
  ["MY", "asia", "Malaysia", "Malaysia", "+60"],
  ["MV", "asia", "Maldives", "Maladewa", "+960"],
  ["MN", "asia", "Mongolia", "Mongolia", "+976"],
  ["MM", "asia", "Myanmar (Burma)", "Myanmar (Burma)", "+95"],
  ["NP", "asia", "Nepal", "Nepal", "+977"],
  ["KP", "asia", "North Korea", "Korea Utara", "+850"],
  ["OM", "asia", "Oman", "Oman", "+968"],
  ["PK", "asia", "Pakistan", "Pakistan", "+92"],
  ["PS", "asia", "Palestinian Territories", "Wilayah Palestina", "+970"],
  ["PH", "asia", "Philippines", "Filipina", "+63"],
  ["QA", "asia", "Qatar", "Qatar", "+974"],
  ["SA", "asia", "Saudi Arabia", "Arab Saudi", "+966"],
  ["SG", "asia", "Singapore", "Singapura", "+65"],
  ["KR", "asia", "South Korea", "Korea Selatan", "+82"],
  ["LK", "asia", "Sri Lanka", "Sri Lanka", "+94"],
  ["SY", "asia", "Syria", "Suriah", "+963"],
  ["TW", "asia", "Taiwan", "Taiwan", "+886"],
  ["TJ", "asia", "Tajikistan", "Tajikistan", "+992"],
  ["TH", "asia", "Thailand", "Thailand", "+66"],
  ["TL", "asia", "Timor-Leste", "Timor Leste", "+670"],
  ["TR", "asia", "Türkiye", "Turki", "+90"],
  ["TM", "asia", "Turkmenistan", "Turkmenistan", "+993"],
  ["AE", "asia", "United Arab Emirates", "Uni Emirat Arab", "+971"],
  ["UZ", "asia", "Uzbekistan", "Uzbekistan", "+998"],
  ["VN", "asia", "Vietnam", "Vietnam", "+84"],
  ["YE", "asia", "Yemen", "Yaman", "+967"],
  ["AL", "europe", "Albania", "Albania", "+355"],
  ["AD", "europe", "Andorra", "Andorra", "+376"],
  ["AT", "europe", "Austria", "Austria", "+43"],
  ["BY", "europe", "Belarus", "Belarus", "+375"],
  ["BE", "europe", "Belgium", "Belgia", "+32"],
  ["BA", "europe", "Bosnia & Herzegovina", "Bosnia dan Herzegovina", "+387"],
  ["BG", "europe", "Bulgaria", "Bulgaria", "+359"],
  ["HR", "europe", "Croatia", "Kroasia", "+385"],
  ["CZ", "europe", "Czechia", "Ceko", "+420"],
  ["DK", "europe", "Denmark", "Denmark", "+45"],
  ["EE", "europe", "Estonia", "Estonia", "+372"],
  ["FI", "europe", "Finland", "Finlandia", "+358"],
  ["FR", "europe", "France", "Prancis", "+33"],
  ["DE", "europe", "Germany", "Jerman", "+49"],
  ["GR", "europe", "Greece", "Yunani", "+30"],
  ["HU", "europe", "Hungary", "Hungaria", "+36"],
  ["IS", "europe", "Iceland", "Islandia", "+354"],
  ["IE", "europe", "Ireland", "Irlandia", "+353"],
  ["IT", "europe", "Italy", "Italia", "+39"],
  ["XK", "europe", "Kosovo", "Kosovo", "+383"],
  ["LV", "europe", "Latvia", "Latvia", "+371"],
  ["LI", "europe", "Liechtenstein", "Liechtenstein", "+423"],
  ["LT", "europe", "Lithuania", "Lituania", "+370"],
  ["LU", "europe", "Luxembourg", "Luksemburg", "+352"],
  ["MT", "europe", "Malta", "Malta", "+356"],
  ["MD", "europe", "Moldova", "Moldova", "+373"],
  ["MC", "europe", "Monaco", "Monako", "+377"],
  ["ME", "europe", "Montenegro", "Montenegro", "+382"],
  ["NL", "europe", "Netherlands", "Belanda", "+31"],
  ["MK", "europe", "North Macedonia", "Makedonia Utara", "+389"],
  ["NO", "europe", "Norway", "Norwegia", "+47"],
  ["PL", "europe", "Poland", "Polandia", "+48"],
  ["PT", "europe", "Portugal", "Portugal", "+351"],
  ["RO", "europe", "Romania", "Rumania", "+40"],
  ["RU", "europe", "Russia", "Rusia", "+7"],
  ["SM", "europe", "San Marino", "San Marino", "+378"],
  ["RS", "europe", "Serbia", "Serbia", "+381"],
  ["SK", "europe", "Slovakia", "Slovakia", "+421"],
  ["SI", "europe", "Slovenia", "Slovenia", "+386"],
  ["ES", "europe", "Spain", "Spanyol", "+34"],
  ["SE", "europe", "Sweden", "Swedia", "+46"],
  ["CH", "europe", "Switzerland", "Swiss", "+41"],
  ["UA", "europe", "Ukraine", "Ukraina", "+380"],
  ["GB", "europe", "United Kingdom", "Inggris Raya", "+44"],
  ["VA", "europe", "Vatican City", "Vatikan", "+39"],
  ["AG", "north-america", "Antigua & Barbuda", "Antigua dan Barbuda", "+1268"],
  ["BS", "north-america", "Bahamas", "Bahama", "+1242"],
  ["BB", "north-america", "Barbados", "Barbados", "+1246"],
  ["BZ", "north-america", "Belize", "Belize", "+501"],
  ["CA", "north-america", "Canada", "Kanada", "+1"],
  ["CR", "north-america", "Costa Rica", "Kosta Rika", "+506"],
  ["CU", "north-america", "Cuba", "Kuba", "+53"],
  ["DM", "north-america", "Dominica", "Dominika", "+1767"],
  ["DO", "north-america", "Dominican Republic", "Republik Dominika", "+1809"],
  ["SV", "north-america", "El Salvador", "El Salvador", "+503"],
  ["GD", "north-america", "Grenada", "Grenada", "+1473"],
  ["GT", "north-america", "Guatemala", "Guatemala", "+502"],
  ["HT", "north-america", "Haiti", "Haiti", "+509"],
  ["HN", "north-america", "Honduras", "Honduras", "+504"],
  ["JM", "north-america", "Jamaica", "Jamaika", "+1658"],
  ["MX", "north-america", "Mexico", "Meksiko", "+52"],
  ["NI", "north-america", "Nicaragua", "Nikaragua", "+505"],
  ["PA", "north-america", "Panama", "Panama", "+507"],
  ["KN", "north-america", "St. Kitts & Nevis", "Saint Kitts dan Nevis", "+1869"],
  ["LC", "north-america", "St. Lucia", "Saint Lucia", "+1758"],
  ["VC", "north-america", "St. Vincent & Grenadines", "Saint Vincent dan Grenadine", "+1784"],
  ["TT", "north-america", "Trinidad & Tobago", "Trinidad dan Tobago", "+1868"],
  ["US", "north-america", "United States", "Amerika Serikat", "+1"],
  ["AU", "oceania", "Australia", "Australia", "+61"],
  ["FJ", "oceania", "Fiji", "Fiji", "+679"],
  ["KI", "oceania", "Kiribati", "Kiribati", "+686"],
  ["MH", "oceania", "Marshall Islands", "Kepulauan Marshall", "+692"],
  ["FM", "oceania", "Micronesia", "Mikronesia", "+691"],
  ["NR", "oceania", "Nauru", "Nauru", "+674"],
  ["NZ", "oceania", "New Zealand", "Selandia Baru", "+64"],
  ["PW", "oceania", "Palau", "Palau", "+680"],
  ["PG", "oceania", "Papua New Guinea", "Papua Nugini", "+675"],
  ["WS", "oceania", "Samoa", "Samoa", "+685"],
  ["SB", "oceania", "Solomon Islands", "Kepulauan Solomon", "+677"],
  ["TO", "oceania", "Tonga", "Tonga", "+676"],
  ["TV", "oceania", "Tuvalu", "Tuvalu", "+688"],
  ["VU", "oceania", "Vanuatu", "Vanuatu", "+678"],
  ["AR", "south-america", "Argentina", "Argentina", "+54"],
  ["BO", "south-america", "Bolivia", "Bolivia", "+591"],
  ["BR", "south-america", "Brazil", "Brasil", "+55"],
  ["CL", "south-america", "Chile", "Cile", "+56"],
  ["CO", "south-america", "Colombia", "Kolombia", "+57"],
  ["EC", "south-america", "Ecuador", "Ekuador", "+593"],
  ["GY", "south-america", "Guyana", "Guyana", "+592"],
  ["PY", "south-america", "Paraguay", "Paraguay", "+595"],
  ["PE", "south-america", "Peru", "Peru", "+51"],
  ["SR", "south-america", "Suriname", "Suriname", "+597"],
  ["UY", "south-america", "Uruguay", "Uruguay", "+598"],
  ["VE", "south-america", "Venezuela", "Venezuela", "+58"],
];
