/**
 * The speakers invited to the tenth ICONZ, in the order the committee lists
 * them, with the profile each one supplied.
 *
 * Kept apart from the rest of the content: this is the longest single body of
 * text on the site and it turns over on its own schedule, as invitations are
 * confirmed and the roster grows toward the twenty-six the programme allows
 * for across the keynote and the panel sessions.
 *
 * The biographies are held in the English they were written in. They are
 * professional records — institutions, degrees, appointments and dates — and
 * a translation of one is a chance to get a name or a title wrong for no gain
 * to a reader who is at an international conference either way. The role under
 * each name is the part that is read at a glance, so that is the part that is
 * carried in both languages.
 */
export type InvitedSpeaker = {
  name: string;
  role: { en: string; id: string };
  bio: string;
  expertise: string[];
  highlights: string[];
};

export const INVITED_SPEAKERS: readonly InvitedSpeaker[] = [
  {
    name: "Dr. Ir. H. Sodik Mudjahid, M.Sc.",
    role: {
      en: "Chairman, National Board of Zakat (BAZNAS RI)",
      id: "Ketua Badan Amil Zakat Nasional (BAZNAS RI)",
    },
    bio: "Dr. Ir. H. Sodik Mudjahid, M.Sc. is the Chairman of the National Zakat Board of the Republic of Indonesia (BAZNAS RI), with extensive experience in Islamic social development, education, public policy, and entrepreneurship. He holds a bachelor's degree in Agricultural Socioeconomics and a master's degree in Agribusiness Management from Universitas Padjadjaran, as well as a doctoral degree in Education Management from Universitas Pendidikan Indonesia. Throughout his career, he has contributed to various sectors, including higher education, community empowerment, entrepreneurship, and national policy. He has served in strategic positions in Indonesia's legislative institutions, educational organizations, and Islamic social institutions. As Chairman of BAZNAS RI, he continues to strengthen the role of zakat as an instrument for poverty alleviation, social empowerment, and sustainable development.",
    expertise: [
      "Zakat Governance and Islamic Social Finance",
      "Public Policy and Community Empowerment",
      "Education Management and Institutional Development",
    ],
    highlights: [
      "Chairman of the National Zakat Board of the Republic of Indonesia (BAZNAS RI)",
      "Former Vice Chairman of Commission VIII of the House of Representatives of the Republic of Indonesia (DPR RI)",
      "Former Member of Commission II and Commission X of DPR RI",
      "Former Vice Chairman of the MPR RI Gerindra Faction",
      "Founder of PT Qiblat Tour, PT Bandung Geriatric Care, PT SAS Aero Sishan, and PT Total Edukasi Indonesia",
      "Chairman of Yayasan Darul Hikam and Chair of Badan Musyawarah Perguruan Swasta",
      "Chairman I of MUI West Java and Advisor of ICMI",
      "Former Deputy Director of Pusat Dakwah Islam (PUSDAI) West Java and Vice Chairman of Dewan Masjid Indonesia",
      "Ph.D. in Education Management, Universitas Pendidikan Indonesia",
      "Master's Degree in Agribusiness Management, Universitas Padjadjaran",
      "Bachelor's Degree in Agricultural Socioeconomics, Universitas Padjadjaran",
    ],
  },
  {
    name: "Prof. Dr. KH. Nasaruddin Umar, M.A.",
    role: {
      en: "Minister of Religious Affairs of Indonesia; Chairman, Association of Islamic Economic Experts (IAEI)",
      id: "Menteri Agama Republik Indonesia; Ketua Ikatan Ahli Ekonomi Islam (IAEI)",
    },
    bio: "Prof. Dr. Nasaruddin Umar, MA is the Minister of Religious Affairs of the Republic of Indonesia and a prominent Islamic scholar with extensive experience in religious affairs, Quranic studies, Islamic education, and public leadership. He also serves as the Grand Imam of Istiqlal Mosque Jakarta and has held various strategic positions in Islamic institutions and government, including Deputy Minister of Religious Affairs and Director General of Islamic Community Guidance. He is a Professor at Universitas Islam Negeri Syarif Hidayatullah Jakarta and Rector of Perguruan Tinggi Ilmu Al-Qur'an (PTIQ) Jakarta. With a strong academic background in Islamic studies and extensive international research experience, he has contributed significantly to the development of Islamic thought, religious moderation, and strengthening Islamic institutions in Indonesia.",
    expertise: [
      "Islamic Studies and Quranic Scholarship",
      "Religious Affairs Policy and Islamic Institutional Development",
      "Islamic Education and Leadership",
    ],
    highlights: [
      "Minister of Religious Affairs of the Republic of Indonesia (2024–present)",
      "Grand Imam of Istiqlal Mosque Jakarta (2016–present)",
      "Chairman of the Istiqlal Mosque Management Board (2021–present)",
      "Former Deputy Minister of Religious Affairs of the Republic of Indonesia (2012–2014)",
      "Former Director General of Islamic Community Guidance, Ministry of Religious Affairs (2006–2012)",
      "Professor at Universitas Islam Negeri Syarif Hidayatullah Jakarta (2005–present)",
      "Rector of Perguruan Tinggi Ilmu Al-Qur'an (PTIQ) Jakarta (2005–present)",
      "Chairman of Ikatan Persaudaraan Imam Masjid Indonesia (IPIM) (2019–present)",
      "Chairman of Pondok Pesantren As'adiyah Sengkang (2022–present)",
      "Former Visiting Scholar at Sophia University, Japan; SOAS University of London, UK; and Visiting Professor at Georgetown University, USA",
      "Ph.D. in Islamic Studies, Universitas Islam Negeri Syarif Hidayatullah Jakarta (1999)",
      "Recipient of various national and international recognitions, including Bintang Karya Satya and International Best Leadership Award (IBLA)",
      "Recognized by MURI for consistent publication of more than 6,000 articles (2021)",
    ],
  },
  {
    name: "Dr. Alim Setiawan Slamet",
    role: { en: "Rector, IPB University", id: "Rektor IPB University" },
    bio: "Dr. Alim Setiawan Slamet is the Rector of IPB University and a distinguished academician with extensive experience in agricultural technology, agribusiness, higher education management, and institutional development. He earned his bachelor's and master's degrees in Agricultural Industrial Technology from IPB University and completed his doctoral degree in Agricultural Marketing and Agribusiness at Ehime University, Japan. Throughout his career at IPB University, he has held various strategic positions, including Vice Rector for Resource Resilience and Infrastructure, Director of Student Affairs and Career Development, and Assistant to the Rector. His expertise and leadership contribute to strengthening higher education governance, sustainable agriculture, innovation, and human resource development. He is also actively involved in professional organizations, including the Agricultural Marketing Society of Japan and the Indonesian Management Forum.",
    expertise: [
      "Higher Education Governance and Leadership",
      "Agribusiness and Sustainable Agricultural Development",
      "Institutional Resilience and Innovation",
    ],
    highlights: [
      "Rector of IPB University",
      "Vice Rector for Resource Resilience and Infrastructure, IPB University (2022–2025)",
      "Director of Student Affairs and Career Development, IPB University (2018–2022)",
      "Head of Rectorate Secretariat Office, IPB University (2013–2014)",
      "Assistant to the Rector of IPB University (2007–2012)",
      "Ph.D. in Agricultural Marketing and Agribusiness, Ehime University, Japan (2017)",
      "Master's Degree in Agricultural Industrial Technology, IPB University (2009)",
      "Bachelor's Degree in Agricultural Industrial Technology, IPB University (2005)",
      "Member of The Agricultural Marketing Society of Japan (2015–present)",
      "Member of Forum Manajemen Indonesia (2017–present)",
    ],
  },
  {
    name: "H. Idy Muzayyad, S.H.I., M.Si.",
    role: {
      en: "Commissioner for Distribution, Utilization and Empowerment, BAZNAS RI",
      id: "Pimpinan Bidang Pendistribusian, Pendayagunaan dan Pemberdayaan, BAZNAS RI",
    },
    bio: "H. Idy Muzayyad, S.H.I., M.Si. is an Islamic philanthropy practitioner with extensive experience in da'wah, communication, media, and zakat management. He currently serves as Commissioner for Distribution, Utilization, and Empowerment at the National Board of Zakat of the Republic of Indonesia (BAZNAS RI). With an academic background in Sharia and Communication Studies, he has contributed to strengthening Islamic social institutions through various roles in media, religious organizations, and philanthropic initiatives. He has been actively involved in the Indonesian Ulema Council (MUI) and currently holds several strategic positions related to Islamic communication, media development, and zakat and waqf advocacy. His work focuses on enhancing the impact of Islamic philanthropy through effective distribution, empowerment programs, and institutional collaboration.",
    expertise: [
      "Zakat Distribution, Utilization, and Empowerment",
      "Islamic Philanthropy and Community Development",
      "Islamic Communication and Media Management",
    ],
    highlights: [
      "Commissioner for Distribution, Utilization, and Empowerment, National Board of Zakat of the Republic of Indonesia (BAZNAS RI) (2026–2031)",
      "Chair of Sharia Supervisory Board, LAZ Investa Amanah (2024–present)",
      "Director of Finance, MUI TV (2025–2030)",
      "Deputy Director of MUI TV (2022–present)",
      "Editor-in-Chief, Majalah Mimbar Ulama (2022–present)",
      "Vice Chair of Information and Communication Commission (INFOKOM), Indonesian Ulema Council (MUI) Central Board (2020–present)",
      "Treasurer, Indonesian Ulema Council (MUI) Central Board (2025–2030)",
      "Chairperson of Yayasan Insan Nusa Madani (2018–present)",
      "Chairperson of Yayasan Rahmatan Lil Alamin Centre Indonesia (2019–present)",
      "Chairperson of Yayasan Jalasurga Indonesia (2022–present)",
      "Vice Chairman, FORJUKAFI (Forum Jurnalis Wakaf dan Zakat Indonesia) (2021–present)",
      "Master's Degree in Communication Studies, Universitas Indonesia (2007)",
      "Bachelor's Degree in Sharia, UIN Sunan Kalijaga Yogyakarta (2003)",
    ],
  },
  {
    name: "H. Syarifuddin, S.Ag., M.E.",
    role: {
      en: "Commissioner for Research, Development, Planning and Innovation, BAZNAS RI",
      id: "Pimpinan Bidang Riset, Pengembangan, Perencanaan dan Inovasi, BAZNAS RI",
    },
    bio: "H. Syarifuddin, S.Ag., M.E. is a zakat practitioner and community empowerment professional with extensive experience in research, program development, education, and social organizations. He currently serves as Commissioner for Research, Development, Planning, and Innovation at the National Board of Zakat of the Republic of Indonesia (BAZNAS RI). Prior to this role, he served as Director of Programs at NU CARE-LAZISNU, where he contributed to the development and implementation of social empowerment programs. With a strong background in Islamic studies, Islamic economics, and community development, he has been actively involved in strengthening zakat institutions, improving program effectiveness, and advancing social impact initiatives through Islamic philanthropy.",
    expertise: [
      "Zakat Management and Islamic Social Finance",
      "Community Empowerment and Social Development Programs",
      "Research, Program Development, and Institutional Innovation",
    ],
    highlights: [
      "Commissioner for Research, Development, Planning, and Innovation, National Board of Zakat of the Republic of Indonesia (BAZNAS RI) (2026–present)",
      "Director of Programs, NU CARE-LAZISNU PBNU (2022–2025)",
      "Director of Operations, PT Sajadah Indomedia Promo (2005–2008)",
      "Program Consultant, PT Vetiga Himais Optima (2010–2013)",
      "Project Officer, Inclusive Voter Education Program, Human Institute – Ministry of Home Affairs (UNDP) (2009)",
      "Assistant Project Officer, LAKPESDAM – The Asia Foundation (2003–2004)",
      "Chairman of Entrepreneurship and MSME Division, Central Board of GP Ansor (2015–2022)",
      "Secretary of Lembaga Kemaslahatan Keluarga NU (LKKNU) (2013–2015)",
      "Deputy Secretary of Lembaga Pendidikan Ma'arif NU (2010–2013)",
      "Master's Degree in Islamic Economics, IAI Tazkia Bogor (2022)",
      "Bachelor's Degree in Sharia, UIN Sunan Kalijaga Yogyakarta (1988)",
    ],
  },
  {
    name: "Dr. Oni Sahroni, M.A.",
    role: {
      en: "Member, National Sharia Council of the Indonesian Ulema Council (DSN-MUI)",
      id: "Anggota Dewan Syariah Nasional Majelis Ulama Indonesia (DSN-MUI)",
    },
    bio: "Dr. Oni Sahroni, M.A. is a prominent Islamic scholar and expert in Islamic jurisprudence, particularly in the field of fiqh muamalah, Islamic finance, and contemporary sharia issues. He serves as a Member of the National Sharia Council of the Indonesian Ulema Council (DSN-MUI) and has contributed extensively to the development of Islamic economic thought, sharia governance, and zakat-related studies. He completed his bachelor's, master's, and doctoral degrees in Fiqh Muqaran with specialization in Fiqh Muamalah at Al-Azhar University, Cairo, with his doctoral dissertation receiving a Summa Cum Laude distinction. Through his academic works, consultations, and involvement in various sharia institutions, he has played an important role in bridging classical Islamic jurisprudence with contemporary economic and financial practices.",
    expertise: [
      "Islamic Jurisprudence and Fiqh Muamalah",
      "Sharia Governance and Islamic Finance",
      "Zakat, Islamic Philanthropy, and Contemporary Economic Issues",
    ],
    highlights: [
      "Member of the National Sharia Council of the Indonesian Ulema Council (DSN-MUI) (2011–present)",
      "Member of Sharia Supervisory Board, Bank Syariah Indonesia (2020–present)",
      "Member of Sharia Supervisory Board, LAZNAS Inisiatif Zakat Indonesia (IZI)",
      "Founder and Advisor, Yayasan Rumah Wasathia",
      "Director, Syariah Consulting Center",
      "Presenter and facilitator of Fiqh Muamalah studies at STEI SEBI and SIBER-C STEI SEBI (2016–present)",
      "Host of Islamic consultation programs, including Muamalah Daily and Republika Sharia Consultation Forum",
      "Recipient of BAZNAS Award as Zakat Supporting Scholar (2023 & 2025)",
      "Recipient of “Best Syariah 2015” / Islamic Scholar Figure Award by Majalah Investor Jakarta",
      "Author of various books on Islamic economics and jurisprudence, including Maqashid Bisnis & Keuangan Islam, Fikih Muamalah Kontemporer, Ushul Fikih Muamalah, and Fikih Zakat Kontemporer",
      "Ph.D. in Fiqh Muqaran (Specialization in Fiqh Muamalah), Al-Azhar University, Cairo (2009)",
      "Master's Degree in Fiqh Muqaran, Al-Azhar University, Cairo (2005)",
      "Bachelor's Degree in Fiqh Muamalah, Al-Azhar University, Cairo (2000)",
    ],
  },
  {
    name: "KH. Miftahul Huda, Lc.",
    role: {
      en: "Secretary, Fatwa Commission, Indonesian Ulema Council (MUI)",
      id: "Sekretaris Komisi Fatwa Majelis Ulama Indonesia (MUI)",
    },
    bio: "KH. Miftahul Huda, Lc. is the Secretary of the Fatwa Commission of the Indonesian Ulema Council (MUI). He has extensive experience in Islamic jurisprudence, religious guidance, and contemporary fatwa development, with particular involvement in issues related to zakat, Islamic finance, halal matters, and emerging social and economic challenges. As Secretary of the MUI Fatwa Commission, he has been actively involved in the formulation, dissemination, and implementation of religious guidance for Indonesian society. His work includes strengthening the role of fatwa as a reference for zakat institutions, particularly in matters concerning zakat collection, management, distribution, and contemporary zakat practices.",
    expertise: [
      "Islamic Jurisprudence and Fatwa Development",
      "Zakat and Islamic Social Finance",
      "Contemporary Islamic Issues and Sharia Governance",
    ],
    highlights: [
      "Secretary, Fatwa Commission of the Indonesian Ulema Council (MUI), 2025–2030",
      "Served as Secretary of the MUI Fatwa Commission during the 2020–2025 period and contributed to the formulation of numerous national fatwas",
      "Member of the drafting team for Himpunan Fatwa Zakat MUI, including the compilation of MUI fatwas on zakat from 1976–2021",
      "Involved in the formulation and dissemination of contemporary zakat fatwas, including fatwas concerning zakat fitrah, zakat on pledged assets, zakat distribution through al-Qardh, and zakat on trade assets",
      "Contributed to MUI fatwa discussions concerning the use of zakat funds for disaster response and humanitarian needs",
      "Regularly represents the MUI Fatwa Commission in public discussions on contemporary Islamic issues and religious guidance",
      "Lecturer and resource person on Islamic jurisprudence and contemporary religious issues",
      "Holds the degree of Lc. in Islamic studies",
    ],
  },
  {
    name: "Mr. Kamarulzaman Bin Omar",
    role: {
      en: "Head of Corporate Strategy Division, Lembaga Zakat Selangor (LZS), Malaysia",
      id: "Kepala Divisi Strategi Korporat, Lembaga Zakat Selangor (LZS), Malaysia",
    },
    bio: "Mr. Kamarulzaman Bin Omar is the Head of Corporate Strategy Division at Lembaga Zakat Selangor (MAIS), Malaysia. He has more than 20 years of professional experience across various industries, including zakat management, banking, retail, courier, and logistics. He has extensive expertise in corporate strategy, transformation management, operational excellence, and organizational performance improvement. Prior to joining Lembaga Zakat Selangor, he served at Pos Malaysia Berhad for 13 years, holding various roles in Corporate Strategy Planning, Transformation Management Office, Quality Management, Innovation, and Finance, with his last position as Financial Controller. He also gained international experience at Harrods Group, London, and in the banking sector through RHB Bank Berhad and MBSB Bank Berhad.",
    expertise: [
      "Zakat Institution Strategy and Governance",
      "Digital Transformation and Operational Excellence",
      "Corporate Strategy and Performance Management",
    ],
    highlights: [
      "Head of Corporate Strategy Division, Lembaga Zakat Selangor (MAIS)",
      "Served at Lembaga Zakat Selangor since September 2019",
      "More than 20 years of experience in corporate strategy, transformation, finance, and organizational improvement",
      "Former Financial Controller at Pos Malaysia Berhad",
      "Former contributor to Corporate Strategy Planning, Transformation Management Office, Quality Management, Innovation, and Finance functions at Pos Malaysia Berhad",
      "Former Management Accountant at Harrods Group, London",
      "Former professional experience in RHB Bank Berhad and MBSB Bank Berhad",
      "Member of Chartered Institute of Management Accountants (CIMA)",
      "Executive Master's in Management, Asia Metropolitan University",
      "Bachelor of Arts (Hons) in Accounting and Finance, Middlesex University, United Kingdom",
    ],
  },
  {
    name: "Prof. Abdul Ghafar Ismail B.Sc., M.Ec., Ph.D.",
    role: {
      en: "Professor, Faculty of Economics and Management, Universiti Kebangsaan Malaysia (UKM)",
      id: "Guru Besar, Fakultas Ekonomi dan Manajemen, Universiti Kebangsaan Malaysia (UKM)",
    },
    bio: "Prof. Abdul Ghafar Ismail is a Professor of Islamic Economics at the Faculty of Economics and Management, Universiti Kebangsaan Malaysia (UKM), and a distinguished scholar in Islamic financial economics. He earned his Ph.D. in Economics from the University of Southampton, United Kingdom, in 1994. With more than three decades of academic and research experience, he has contributed extensively to the fields of Islamic banking, Islamic finance, zakat, waqf, microfinance, financial inclusion, and socio-economic development. He has held various strategic positions, including Lead Researcher at the Islamic Research and Training Institute (IRTI), Islamic Development Bank in Jeddah, Rector of Kolej Pengajian Islam Johor, and Professor of Islamic Financial Economics at several universities. His research has been widely published in international peer-reviewed journals and he has authored numerous books on Islamic finance and social finance.",
    expertise: [
      "Islamic Economics and Islamic Financial Systems",
      "Zakat, Waqf, and Islamic Social Finance",
      "Islamic Banking, Financial Inclusion, and Poverty Alleviation",
    ],
    highlights: [
      "Professor of Islamic Economics, Faculty of Economics and Management, Universiti Kebangsaan Malaysia (UKM)",
      "Chairman of the Organisation of Islamic Studies and Thoughts",
      "AmBank Group Resident Fellow, Perdana Leadership Foundation",
      "Citibank Malaysia Shariah Advisor (2005–present)",
      "Former Lead Researcher, Islamic Research and Training Institute (IRTI), Islamic Development Bank, Jeddah (2013–2017)",
      "Former Rector, Kolej Pengajian Islam Johor (2019–2020)",
      "Former Professor of Islamic Financial Economics at Universiti Islam Sultan Sharif Ali, Brunei",
      "Advisor and consultant for various Islamic economics and social finance initiatives, including Islamic Economics Master Plan for Indonesia, National Cooperative Policy, Microfinancing Action Plan, and Amanah Ikhtiar Malaysia Action Plan",
      "Author of numerous books, including Islamic Philanthropy: Exploring Zakat, Waqf, and Sadaqah in Islamic Finance and Economics; Financial Inclusion and Poverty Alleviation; and Economic Capital and Risk Management in Islamic Finance",
      "Ph.D. in Economics, University of Southampton, United Kingdom (1994)",
    ],
  },
  {
    name: "Prof. Dr. Irfan Syauqi Beik",
    role: {
      en: "Deputy Secretary General, World Zakat & Waqf Forum; Dean, Faculty of Economics and Management, IPB University",
      id: "Wakil Sekretaris Jenderal World Zakat & Waqf Forum; Dekan Fakultas Ekonomi dan Manajemen IPB University",
    },
    bio: "Prof. Dr. Irfan Syauqi Beik is a prominent scholar and practitioner in the field of Islamic economics, Islamic social finance, and zakat development. He currently serves as Dean of the Faculty of Economics and Management at IPB University, Indonesia, and Deputy Secretary General of the World Zakat & Waqf Forum (WZWF). He earned his bachelor's degree in Agribusiness from IPB University, followed by a master's degree in Islamic Economics from International Islamic University Islamabad, Pakistan, and a doctoral degree in Islamic Economics from International Islamic University Malaysia. With extensive experience in academia, policy, and Islamic social finance institutions, he has contributed significantly to the development of zakat, waqf, poverty alleviation, and Islamic economic studies in Indonesia and globally. He is also the founder of CIBEST, an Islamic economic framework for measuring poverty and welfare from both material and spiritual perspectives.",
    expertise: [
      "Islamic Social Finance, Zakat, and Waqf",
      "Islamic Economics and Poverty Alleviation",
      "Islamic Economic Development and Policy",
    ],
    highlights: [
      "Dean, Faculty of Economics and Management, IPB University, Indonesia",
      "Deputy Secretary General, World Zakat & Waqf Forum (WZWF) (2023–2026)",
      "Former Director of Distribution and Utilization, BAZNAS RI",
      "Founder of Center for Islamic Business and Economic Studies (CIBEST), IPB University",
      "Chairman, Center for Islamic Business and Economic Studies, LPPM IPB University",
      "Commissioner, Indonesian Waqf Board (BWI)",
      "Member of National Sharia Council of Indonesian Ulema Council (DSN-MUI)",
      "Chairman of the Center for Waqf Studies and Digital Transformation, Indonesian Waqf Board (2021–2024)",
      "Recipient of Bank Indonesia Award (BI Award) 2021 as Outstanding Figure in Islamic Social Economy Development",
      "Recipient of Anugerah Kemandirian 2020 from Yatim Mandiri National Zakat Institution",
      "Ph.D. in Islamic Economics, International Islamic University Malaysia (2010)",
      "Master's Degree in Islamic Economics, International Islamic University Islamabad, Pakistan (2005)",
      "Bachelor's Degree in Agribusiness, IPB University (2002)",
    ],
  },
  {
    name: "Dr. Muhsin Nor Paizin",
    role: {
      en: "Senior Manager, Zakat Academy (AZKA-PPZ), Pusat Pungutan Zakat – MAIWP, Malaysia",
      id: "Senior Manager, Zakat Academy (AZKA-PPZ), Pusat Pungutan Zakat – MAIWP, Malaysia",
    },
    bio: "Dr. Muhsin Nor Paizin is the Senior Manager of Zakat Academy (AZKA-PPZ) at Pusat Pungutan Zakat (PPZ-MAIWP), Malaysia, with expertise in zakat research, Islamic social finance, policy innovation, and knowledge development. He leads initiatives in research, education, and public engagement to strengthen zakat governance and enhance the role of zakat in socio-economic development. He holds a Ph.D. in Islamic Management from the University of Malaya and has extensive experience in developing evidence-based strategies, digital learning initiatives, and collaborative platforms for Islamic social finance. Through AZKA-PPZ, he contributes to advancing zakat knowledge through research publications, capacity-building programs, and engagement with academic institutions, practitioners, and policymakers.",
    expertise: [
      "Zakat Research and Islamic Social Finance",
      "Zakat Governance and Policy Innovation",
      "Knowledge Management, Digital Learning, and Capacity Development",
    ],
    highlights: [
      "Senior Manager of Zakat Academy (AZKA-PPZ), Pusat Pungutan Zakat – MAIWP (2025–present)",
      "Acting Assistant General Manager of Human Capital Development, Performance & Research, PPZ-MAIWP (2025–present)",
      "Former Manager of Zakat Academy (AZKA-PPZ) (2022–2025)",
      "Former Assistant Manager and Research Executive at AZKA-PPZ, leading research and knowledge development initiatives (2012–2022)",
      "Founder and manager of AZKA International Journal of Zakat & Social Finance (AZJAF), supporting academic knowledge exchange in zakat and Islamic social finance",
      "Developed digital learning programs on Islamic social finance and conducted zakat-related public engagement initiatives through webinars and knowledge-sharing platforms",
      "Established zakat knowledge initiatives, including specialized zakat reading corners in universities and AZKA resource portal development",
      "External Assessor for Diploma in Zakat and Waqf Management Program, MAIWP Professional College",
      "Ph.D. in Islamic Management, University of Malaya",
      "Master's Degree in Islamic Studies, University of Malaya",
      "Bachelor of Business Administration in International Business, Universiti Teknologi MARA",
    ],
  },
  {
    name: "Mr. Mawlana Adil Bader",
    role: {
      en: "Zakat Operations Lead, Islamic Relief Worldwide; Founder & Director, Zamil Consultancy, UK",
      id: "Zakat Operations Lead, Islamic Relief Worldwide; Pendiri & Direktur Zamil Consultancy, Inggris",
    },
    bio: "Mr. Mawlana Adil Bader is a humanitarian programme and governance professional specializing in zakat operations, Islamic social finance, and institutional development. He currently serves as Zakat Operations Lead at Islamic Relief Worldwide, where he is responsible for strengthening zakat governance, policy implementation, and operational compliance across the organization's global network. He is also the Founder and Director of Zamil Consultancy, a UK-based consultancy specializing in zakat governance, compliance, institutional design, and capacity building. With experience bridging Islamic jurisprudence, humanitarian operations, and organizational governance, he works to develop credible, accountable, and scalable zakat systems that support effective social impact.",
    expertise: [
      "Zakat Governance and Compliance",
      "Humanitarian Operations and Islamic Social Finance",
      "Institutional Development and Capacity Building",
    ],
    highlights: [
      "Zakat Operations Lead, Islamic Relief Worldwide (2023–present)",
      "Founder & Director, Zamil Consultancy, specializing in Zakat Governance, Compliance, and Institutional Design (2025–present)",
      "Leads zakat governance implementation across 40+ Islamic Relief country offices through policy development, assurance frameworks, and organizational capability building",
      "Develops global zakat policies, training strategies, and executive advisory frameworks to strengthen institutional zakat practices",
      "Provides consultancy and training for zakat organizations, humanitarian agencies, foundations, and emerging zakat institutions on governance and accountability systems",
      "Certified Expert in Islamic Microfinance, Frankfurt School of Finance & Management (2019)",
      "Project Management Certification, Cornell University (2016)",
      "Bachelor of Science in Human Biology, University of Birmingham (2012)",
    ],
  },
  {
    name: "Dr. Elnur Salihovic",
    role: {
      en: "Deputy Secretary General, World Zakat & Waqf Forum (WZWF), Bosnia and Herzegovina",
      id: "Wakil Sekretaris Jenderal World Zakat & Waqf Forum (WZWF), Bosnia dan Herzegovina",
    },
    bio: "Dr. Elnur Salihovic is an international expert in Islamic finance, philanthropy, zakat management, and global partnerships. He currently serves as Deputy Secretary General of the World Zakat and Waqf Forum (WZWF) and has extensive experience in developing international collaborations, strategic initiatives, humanitarian programs, and social finance innovations. He previously served as Head of Zakat Office at the Riyasat of Islamic Community in Bosnia and Herzegovina and has been involved in global humanitarian initiatives through Médecins Sans Frontières (MSF) and UNICEF. He is also recognized as an author in Islamic philanthropy and zakat studies, including publications on zakat practices and Muslim communities. His work focuses on strengthening the role of zakat and philanthropy as instruments for sustainable social development and global cooperation.",
    expertise: [
      "Zakat Governance and Islamic Philanthropy",
      "International Partnerships and Humanitarian Development",
      "Islamic Finance and Social Impact Innovation",
    ],
    highlights: [
      "Deputy Secretary General, World Zakat and Waqf Forum (WZWF) (2014–present)",
      "Advisor, Consultant, and Project Manager, Médecins Sans Frontières (MSF) (2022–present)",
      "Consultant, UNICEF Geneva (2018–2020)",
      "Former Head of Zakat Office, Riyasat of Islamic Community in Bosnia and Herzegovina (2007–2018)",
      "Former Member of the Supervisory Board, Energoinvest Sarajevo (2016–2023)",
      "Contributor to the establishment of the Global Muslim Philanthropy Fund for Children, a joint initiative between UNICEF and the Islamic Development Bank (IsDB)",
      "Author of books including Major Players in the Muslim Business World and Zakat in Theory and Practice of Muslims in Bosnia and Herzegovina and the World",
      "Ph.D. in Islamic Studies, University of Sarajevo (2017)",
      "Master's Degree in State Management, Sapienza Università di Roma (2002–2003)",
      "Bachelor's Degree in Islamic Studies, University of Sarajevo (1996–2001)",
    ],
  },
  {
    name: "Haji Azrin bin Dato' Haji Abdul Manan",
    role: {
      en: "Deputy Chief Executive Officer, Pusat Pungutan Zakat – MAIWP, Malaysia",
      id: "Wakil Chief Executive Officer, Pusat Pungutan Zakat – MAIWP, Malaysia",
    },
    bio: "Haji Azrin bin Dato' Haji Abdul Manan is the Deputy Chief Executive Officer of Pusat Pungutan Zakat – Majlis Agama Islam Wilayah Persekutuan (PPZ-MAIWP), Malaysia. He has extensive experience in organizational management, human capital development, and institutional operations, with more than three decades of professional experience. Prior to his current role, he served as Senior General Manager of Human Resources at PPZ-MAIWP for more than 13 years, contributing to organizational development, talent management, and institutional strengthening. He previously held the position of Human Resources General Manager at Hartasuci, where he gained extensive experience in people management and corporate administration. With a strong background in management and accounting, he continues to contribute to strengthening the operational effectiveness and governance of zakat institutions.",
    expertise: [
      "Zakat Institution Management and Operations",
      "Human Capital Development and Organizational Management",
      "Strategic Management and Institutional Governance",
    ],
    highlights: [
      "Deputy Chief Executive Officer, Pusat Pungutan Zakat – MAIWP (PPZ-MAIWP) (2025–present)",
      "Senior General Manager Human Resources, PPZ-MAIWP (2012–2025)",
      "Human Resources General Manager, Hartasuci (1993–2021)",
      "Experienced in people management, industrial relations, and conflict resolution",
      "Bachelor's Degree in Accounting, Universiti Kebangsaan Malaysia (1989–1993)",
      "Diploma in Business Studies (Accounting and Business Management), Universiti Teknologi MARA (1986–1989)",
    ],
  },
  {
    name: "H.E. Datuk Dr. Mohd. Ghazali bin Md. Noor",
    role: {
      en: "General Secretary, World Zakat & Waqf Forum (WZWF)",
      id: "Sekretaris Jenderal World Zakat & Waqf Forum (WZWF)",
    },
    bio: "Datuk Dr. Mohd. Ghazali bin Md. Noor is the General Secretary of the World Zakat and Waqf Forum (WZWF) and an internationally recognized expert in Islamic development, waqf, and Islamic finance. He has extensive experience in public administration, international development, and Islamic social finance, including his service at the Islamic Development Bank (IsDB) in Jeddah from 1996 to 2009. During his tenure at IsDB, he led the IDB Scholarship Program, supporting the selection and development of international students from 56 countries in science and technology fields. He has also contributed significantly to global waqf development through the establishment of corporate waqf frameworks, leadership in the Global Waqf Conference, and his role in international waqf initiatives. His expertise and leadership have positioned him as a prominent figure in advancing zakat and waqf institutions globally.",
    expertise: [
      "Waqf Development and Islamic Social Finance",
      "International Islamic Development and Partnership",
      "Public Administration and Institutional Governance",
    ],
    highlights: [
      "General Secretary, World Zakat and Waqf Forum (WZWF)",
      "Former Deputy Secretary General, World Zakat and Waqf Forum (WZWF) (2022–present)",
      "Former Official at Islamic Development Bank (IsDB), Jeddah (1996–2009)",
      "Former Head of IDB Scholarship Program, managing international scholarship selection from 56 countries",
      "Developed Corporate Waqf Plan for a prominent Malaysian waqf-based foundation (2011)",
      "Director and Lead Organizer of Global Waqf Conference (GWC) (2013–present)",
      "Interim Chairman of International Waqf Action Council (iWAQF), established in Malaysia (2018)",
      "Former Board Member of Awqaf Holdings, a pioneer in corporate waqf initiatives in Malaysia",
      "Former Member of Majlis Agama Islam Wilayah Persekutuan Malaysia (2021–2022)",
      "Chairman of the 11th Global Waqf Conference (2023), Istanbul, Türkiye",
      "Ph.D. in Public Administration, University of Southern California, Los Angeles, USA",
      "Bachelor's Degree in Economics and Administration, University of Malaya (1970–1973)",
    ],
  },
  {
    name: "Prof. Mohammad Nabil Almunawar",
    role: {
      en: "Professor, Universiti Brunei Darussalam",
      id: "Guru Besar, Universiti Brunei Darussalam",
    },
    bio: "Prof. Mohammad Nabil Almunawar is a Professor of Business and Management at Universiti Brunei Darussalam (UBD), Brunei Darussalam, with more than three decades of experience in higher education, information technology, digital transformation, and business management. He previously served as Dean of the UBD School of Business and Economics and was recognized as one of the exemplary lecturers of UBD during its 25th anniversary celebration, receiving an award from His Majesty Sultan Haji Hassanal Bolkiah. He holds a Ph.D. in Computer Science and Engineering from the University of New South Wales, Australia, and a Master's degree in Computer Science from the University of Western Ontario, Canada. His research focuses on digital transformation, e-commerce, e-business, information systems, and technology adoption for organizational development. He has published more than 100 academic papers and numerous books on digital economy, technology management, and organizational transformation.",
    expertise: [
      "Digital Transformation and Information Systems",
      "E-Commerce, E-Business, and Digital Economy",
      "Business Management and Technology Innovation",
    ],
    highlights: [
      "Professor of Business and Management, Universiti Brunei Darussalam (UBD)",
      "Former Dean, UBD School of Business and Economics (SBE)",
      "Recipient of UBD Exemplary Lecturer Award during the 25th Anniversary of Universiti Brunei Darussalam, presented by His Majesty Sultan Haji Hassanal Bolkiah",
      "More than 30 years of teaching and research experience in computer science, information systems, and business management",
      "Author of more than 15 books in recent years, including Digitalisation and Organisation Design Knowledge Management in the Asian Digital Economy and Digital Transformation Management: Challenges and Futures in the Asian Digital Economy",
      "Published more than 100 research papers in journals, books, and international conference proceedings",
      "Research focus includes IT applications in management, e-commerce, e-business, e-government, multimedia information retrieval, and information security",
      "Ph.D. in Computer Science and Engineering, University of New South Wales (UNSW), Australia (1997)",
      "Master's Degree in Computer Science, University of Western Ontario, Canada (1991)",
      "Bachelor's Degree in Agricultural Industrial Technology, IPB University, Indonesia (1983)",
    ],
  },
  {
    name: "Prof. Dr. Ir. Muhammad Firdaus, SP, M.Si.",
    role: { en: "Professor, IPB University", id: "Guru Besar, IPB University" },
    bio: "Prof. Dr. Ir. Muhammad Firdaus, SP, M.Si. is a Professor at IPB University with expertise in agricultural economics, international trade, agribusiness, and agricultural policy. He earned his doctoral degree in Economics from Universiti Putra Malaysia in 2006 and was appointed as Professor of Economics at IPB University in 2013. Throughout his academic career, he has contributed to research, policy development, and innovation in agriculture, particularly in strengthening farmers' competitiveness and improving agricultural business systems. He is the creator of the Sistem Informasi Kelayakan Usaha Hortikultura (SIKUH), an innovative information system that supports farmers, extension workers, and agribusiness actors in assessing the economic feasibility of horticultural farming. He has also contributed at national and international levels through his involvement in agricultural trade policy, including as a member of the Indonesian WTO Agricultural Policy Research Team and as an education and culture attaché of the Republic of Indonesia in Kuala Lumpur.",
    expertise: [
      "Agricultural Economics and Agribusiness Development",
      "International Trade and Agricultural Policy",
      "Innovation, Digital Agriculture, and Farmer Empowerment",
    ],
    highlights: [
      "Professor of Economics, IPB University (appointed 2013)",
      "Education and Culture Attaché of the Republic of Indonesia in Kuala Lumpur (2022–present)",
      "Former Vice Dean, Faculty of Economics and Management, IPB University",
      "Head of Marketing and Cooperation Division, Center for Tropical Horticulture Studies (PKHT), IPB University",
      "Member of Indonesia's WTO Agricultural Policy Research Team",
      "Policy Research Team Member for the Ministry of Manpower of the Republic of Indonesia",
      "Former Vice Chairman of Permanent Committee for Horticulture, Indonesian Chamber of Commerce and Industry (KADIN)",
      "Former Chairman of South East Asian International Trade and Finance Association",
      "Chairman of Expert Council, Himpunan Alumni IPB",
      "Founder of Sistem Informasi Kelayakan Usaha Hortikultura (SIKUH), a digital platform supporting horticultural business feasibility analysis and agricultural decision-making",
      "Recipient of six National Intellectual Property Awards (KIN) from the Directorate General of Intellectual Property for SIKUH (2012–2016)",
      "Ph.D. in Economics, Universiti Putra Malaysia (2006)",
      "Guru Besar IPB University with scientific oration in Economics (2013)",
    ],
  },
  {
    name: "Mr. Fariz Ubaidullah bin Mahamud",
    role: {
      en: "Director, Baitulmal Division, Department of Awqaf, Zakat and Hajj (JAWHAR), Malaysia",
      id: "Direktur Divisi Baitulmal, Jabatan Wakaf, Zakat dan Haji (JAWHAR), Malaysia",
    },
    bio: "Mr. Fariz Ubaidullah bin Mahamud is the Director of the Baitulmal Division at the Department of Awqaf, Zakat and Hajj (JAWHAR), Malaysia. He has extensive experience in public administration, policy and strategic planning, with professional exposure across government institutions and Islamic social finance. In his current role at JAWHAR, he contributes to the strengthening of Baitulmal management, including the development, coordination, and strategic implementation of initiatives related to zakat and public Islamic funds. He previously served in Malaysia's National Disaster Management Agency (NADMA), where he was involved in planning and policy functions, including participation in international and regional disaster risk reduction initiatives. His cross-sector experience provides a perspective on institutional coordination, policy development, and strengthening public-sector approaches to Islamic social finance.",
    expertise: [
      "Baitulmal, Zakat and Islamic Social Finance",
      "Public Policy and Strategic Planning",
      "Institutional Coordination and Governance",
    ],
    highlights: [
      "Director, Baitulmal Division, Department of Awqaf, Zakat and Hajj (JAWHAR), Malaysia",
      "Former Senior Principal Assistant Director, Planning & Policy Division, National Disaster Management Agency (NADMA), Malaysia",
      "Experienced in government policy development, strategic planning, and inter-agency coordination",
      "Participated in international and regional forums on disaster risk reduction and public policy, including the Global Platform for Disaster Risk Reduction",
      "Contributes to national-level development and coordination of Baitulmal, zakat, and Islamic social finance management through JAWHAR",
    ],
  },
  {
    name: "Lawal Maidoki",
    role: {
      en: "Executive Chairman, Sokoto State Zakat and Waqf Commission (SOZECOM), Nigeria",
      id: "Ketua Eksekutif Sokoto State Zakat and Waqf Commission (SOZECOM), Nigeria",
    },
    bio: "Lawal Maidoki is a Nigerian zakat and waqf practitioner who serves as Executive Chairman of the Sokoto State Zakat and Waqf (Endowment) Commission (SOZECOM). He has extensive experience in zakat management, Islamic social finance, poverty alleviation, community development, and institutional transformation. As the leader of SOZECOM, he has contributed to strengthening zakat and waqf administration in Sokoto State, including efforts to improve institutional capacity and explore digital finance for zakat and waqf management. He has also been actively involved in international knowledge exchange and collaboration on zakat and waqf, including cooperation between SOZECOM and BAZNAS Indonesia.",
    expertise: [
      "Zakat and Waqf Management",
      "Islamic Social Finance and Poverty Alleviation",
      "Institutional Development and Digital Transformation",
    ],
    highlights: [
      "Executive Chairman, Sokoto State Zakat and Waqf (Endowment) Commission (SOZECOM), Nigeria",
      "Deputy Secretary General, World Zakat and Waqf Forum (WZWF)",
      "Former Agricultural Engineer at Sokoto Rima Basin Development Authority",
      "Led initiatives to strengthen SOZECOM's institutional capacity and explore digital finance for zakat and waqf administration",
      "Co-authored research on the role of Islamic social finance in empowering youth and women in Sokoto State",
      "Co-authored research examining the impact of zakat distribution on poverty reduction in Sokoto State",
      "Author of research on zakat and waqf as instruments for social welfare and poverty alleviation in Sokoto State",
      "Engaged in knowledge exchange and institutional cooperation between SOZECOM and BAZNAS Indonesia on zakat and waqf management",
      "Participated in international zakat and waqf forums and capacity-building initiatives involving organizations from multiple countries",
    ],
  },
  {
    name: "Achmad Setio Adinugroho, S.Si, M.IT.",
    role: {
      en: "Director of Innovation and Information Technology, BAZNAS RI",
      id: "Direktur Inovasi dan Teknologi Informasi, BAZNAS RI",
    },
    bio: "Achmad Setio Adinugroho is the Director of Innovation and Information Technology at the National Board of Zakat of the Republic of Indonesia (BAZNAS RI), with expertise in information technology, software engineering, digital systems, and technology-driven organizational transformation. He has extensive experience in developing digital solutions, managing IT systems, and evaluating information technology infrastructure, particularly within nonprofit organizations. Prior to his role at BAZNAS RI, he founded and led technology initiatives through Phico Technology and Code in Design, focusing on software development, web technologies, and IT solutions. With a strong background in technology management, he contributes to accelerating digital transformation and strengthening technology-based governance within zakat institutions.",
    expertise: [
      "Digital Transformation and Information Technology Governance",
      "Software Engineering and Application Development",
      "IT Systems Management and Innovation",
    ],
    highlights: [
      "Director of Innovation and Information Technology, National Board of Zakat of the Republic of Indonesia (BAZNAS RI) (2021–present)",
      "Founder and CEO/CISO, Phico Technology (2007–present)",
      "Administrator and Author, Code in Design (2009–present), focusing on web development and technology-related publications",
      "Experienced in evaluating and auditing information technology systems for nonprofit organizations, including BAZNAS Indonesia",
      "Expertise in software engineering, application analysis, DHTML, JavaScript/jQuery, PHP, and MySQL",
      "Master's Degree in Information Technology, Macquarie University (2007–2008)",
      "Bachelor's Degree in Astronomy, Institut Teknologi Bandung (2000–2005)",
    ],
  },
  {
    name: "Dr. Yuli Yasin, Lc., M.A.",
    role: {
      en: "Dean, Faculty of Islamic Studies (Dirasat Islamiyah), UIN Syarif Hidayatullah",
      id: "Dekan Fakultas Dirasat Islamiyah, UIN Syarif Hidayatullah",
    },
    bio: "Dr. Yuli Yasin, Lc., M.A. is the Dean of the Faculty of Dirasat Islamiyah at UIN Syarif Hidayatullah Jakarta and a scholar specializing in Islamic Sharia, Islamic jurisprudence, and contemporary Islamic legal studies. He previously served as Vice Dean for Academic Affairs at the same faculty before being appointed Dean in 2023. He completed his undergraduate and postgraduate education in Islamic Sharia in Egypt, earning his bachelor's degree from Al-Azhar University, master's degree from Cairo University, and doctoral degree from Darul Ulum University, Cairo. His academic work focuses particularly on Islamic law, contemporary fatwas, fiqh, and waqf. His doctoral dissertation examined the problems of waqf in Indonesia and their solutions from the perspective of Islamic law.",
    expertise: [
      "Islamic Sharia and Fiqh",
      "Waqf and Islamic Philanthropy",
      "Contemporary Islamic Law and Fatwas",
    ],
    highlights: [
      "Dean, Faculty of Dirasat Islamiyah, UIN Syarif Hidayatullah Jakarta (2023–present)",
      "Former Vice Dean for Academic Affairs, Faculty of Dirasat Islamiyah, UIN Syarif Hidayatullah Jakarta",
      "Head of Sharia Supervisory Board, Social Trust Fund (STF) UIN Syarif Hidayatullah Jakarta",
      "Lecturer and Head Lecturer in Islamic Sharia at the Faculty of Dirasat Islamiyah, UIN Syarif Hidayatullah Jakarta",
      "Teaches courses including Fiqh al-Kitab wa al-Sunnah, Fiqh Mazhab, Contemporary Fatwas in the Muslim World, and Thematic Study of Hadith",
      "Published research on waqf, including studies on cash waqf, temporary cash waqf, and waqf-linked sukuk for social and economic development",
      "Ph.D. in Islamic Sharia, Darul Ulum University, Cairo (2015)",
      "Master's Degree in Islamic Sharia, Cairo University (2004)",
      "Bachelor's Degree in Islamic Sharia, Al-Azhar University, Cairo (1997)",
    ],
  },
  {
    name: "Prof. Dr. H. Waryono Abdul Ghofur, M.Ag.",
    role: {
      en: "Director of Zakat and Waqf Empowerment, Ministry of Religious Affairs of the Republic of Indonesia",
      id: "Direktur Pemberdayaan Zakat dan Wakaf, Kementerian Agama Republik Indonesia",
    },
    bio: "Prof. Dr. H. Waryono Abdul Ghofur, M.Ag. is an academic and Islamic scholar specializing in Qur'anic exegesis and the study of religions. He is a lecturer at the Graduate School of UIN Sunan Kalijaga Yogyakarta, where he teaches Tafsir and contributes to the development of contemporary Islamic scholarship. He completed his undergraduate, master's, and doctoral education at UIN Sunan Kalijaga, with academic specialization in Islamic studies, religion and philosophy, and Qur'anic studies. Alongside his academic career, he serves as Director of Zakat and Waqf Empowerment at the Ministry of Religious Affairs of the Republic of Indonesia, where he contributes to strengthening the management and empowerment of zakat and waqf as instruments for community welfare and economic empowerment.",
    expertise: [
      "Qur'anic Exegesis and Islamic Studies",
      "Zakat and Waqf Empowerment",
      "Religious Studies and Islamic Thought",
    ],
    highlights: [
      "Director of Zakat and Waqf Empowerment, Ministry of Religious Affairs of the Republic of Indonesia",
      "Lecturer, Graduate School, UIN Sunan Kalijaga Yogyakarta",
      "Lecturer in Tafsir and Qur'anic Studies",
      "Academic and researcher in Islamic studies, religious studies, and contemporary Islamic thought",
      "Contributor to academic publications on zakat, waqf, and religious thought in Indonesia",
      "Bachelor's Degree, Faculty of Ushuluddin, UIN Sunan Kalijaga Yogyakarta",
      "Master's Degree, Religion and Philosophy, UIN Sunan Kalijaga Yogyakarta",
      "Doctoral Degree in Islamic Studies, UIN Sunan Kalijaga Yogyakarta",
    ],
  },
];
